<div class="content col-md-8" id="content">
	<b><h1 style="font-size:180%" class="section-title">FOFJ Faces Greater Challenges and Charts New Milestones in the New Millennium</h2></b>
	<pre style="font-size:150%">The Flames of Fire for Jesus scored several milestone achievements in the Jubilee Year 2000. On its 23rd  anniversary celebration in January 2000, FOFJ came out with the maiden issue of its newsletter "The Flame". The quarterly newsletter highlights the accomplishments and achievements of the FOFJ ministries and communities during the previous quarter and their plans and programs for the future. By focusing on these achievements, The Flame aims to inspire the other communities that there is more work to be done and that no matter how difficult the task may be, all things will work out for the good of those who love the Lord.

Another big achievement was the successful convening of the FOFJ Youth Convention 2000 at Villa Manaog in Pandi, Bulacan. An estimated 500 youth participants and FOFJ workers attended the 3-day convention which was so far the biggest and most  expensive.  Six months later, FOFJ held a Youth Big Day in Bolinao, Pangasinan.

Many new things were also implemented during the year to foster closer relationships and greater participation of FOFJ communities and ministries in Center activities. These include holding quarterly global gatherings instead of the previous two events (Anniversary and Christmas) and the monthly First Saturday Prayer and Fasting that had to be conceptualized and sponsored by the local communities and ministries.

FOFJ accelerated its pace in 2001, guided by a prophetic vision of a safari jeep traveling at a very fast speed towards a mountain. The jeep later disappeared in a large cloud of dust. The message impressed from the vision was God wants the FOFJ to accelerate its work so that the Community can keep pace with the work God wants the FOFJ  to accomplish. God (in the safari jeep) is leading the way but it seems that the FOFJ has lagged far behind. The FOFJ must accelerate its pace or else the cloud of dust will hamper its view and progress or worse, impair its eyesight causing it not to see the dangers that lie ahead.

God truly worked in a different way to achieve His purpose of accelerating His work. The First Summer Convention of the Professionals for Jesus was held simultaneously with the Youth Convention and the MR Convention at the Villa Manaog Retreat House in March 2001. What used to be a youth-oriented activity now became a three-pronged activity aimed at evangelizing the youth, professionals and couples.The summer mission work among the Aetas in Porac was transformed into a fulltime mission assignment. FOFJ was invited to help in operating the resettlement school in Porac. Thus, in school year 2001-2002,FOFJ sent four young men and women to serve as fulltime teachers and missionaries in the resettlement area.

The MR ministry and the BPI office ministry conducted a Christmas party/giftgiving program and an agri-livelihood outreach mission, respectively, in Porac. A YFJ group was also formed in the Porac resettlement area. In October 2001, FOFJconducted a 2-day leadership training seminar in San IIdefonso, Bulacan that was attended by 16 potential Aeta youth leaders. The seminar focused on drawing the participants closer to God, raising potential leaders, and inspiring them to hope and aspire for a better future believing that God wants them to experience life to the fullest.

During the year, the YFJ also achieved its goal to have 500 members in its campus ministries in Metro Manila in school year 2001-2002. It was also in 2001 that Nap started his street children ministry at his office in Sta. Cruz, Manila. In September 2001, the various MR groups of FOFJ held an MR Leaders' Retreat as their first joint activity to further strengthen the role and impact of MR groups in bringing about changes in families and communities.

In 2002, FOFJ continued to implement new strategies to further accelerate its mission work. Unlike the big global youth conventions in the previous years, FOFJ simultaneously held youth conventions in Bulacan and Pampanga. The 2002 Summer Youth Convention held in San IIdefonso, Bulacan was limited to YFJ campus members from selected YFJ campus ministries. Participants were inspired to live a balanced life filled with the presence and empowerment of the Lord Jesus. After the YFJ Campus Youth Convention, a one-day Bulacan Youth Camp was held for high school and college students living in several barangays  in San IIdefonso. While the Bulacan Youth Camp was ongoing, the FOFJ was also conducting its first Aeta Youth Convention at the Villa Maria resettlement area. The South Community meanwhile, held its biggest youth conventionin May 2002 at DOST in Bicutan that was attended by about 150 high school and college students.

The fourth Aeta Summer Literacy Program in 2002 was also different from those held in the previous years. For the first time, FOFJ hired nine Aeta high school students as assistant teachers to help the YFJ missionary teachers. Classes were held inside the classroom instead of the open fields or under the trees.

In July 2002, ten FOFJ Center members working in Makati formed The Makati Group (TMG). Its mission is to bring God to the workplace and the Good News to the professional world. TMG meets every Wednesday after office hours at the Don Bosco Parish Church.

In his anniversary message in January 2003, Kuya Mon exhorted the Community that God's marching orders to "Go and make disciples of all nations" have not been rescinded despite the uncertainties  brought about by the unstable global economic and
political situation.

Thus by the end of school year 2002-2003, YFJ exceeded its goal to raise 1,000 members. YFJ expanded its territories in  school year 2003-2004 not only in Metro Manila but also across the sea to the Visayas region. Two FOFJ missionaries, BengTacda and Arla Montes, started in May 2003 their mission work in Iloilo to evangelize in schools and establish YFJ ministries. By August 2003, they had 30 active members and six regular cell groups in the West Visayas State University.

To raise more YFJ workers andmembers, FOFJ held its annual youth conventions in Bulacan, Pampanga, and DOST for its various YFJ campus ministries and local communities.

To strengthen the FOFJ Prophetic Ministry, Kuya Mon conducted Prophetic Conferences for the Professional Group in June and for the YFJ in August. Likewise, a healing and miracle conference for YFJ  was held in August  to activate and release the gift of healing.

FOFJ continued to do new things for the Lord in 2003. In July, the YFJ held its first Worship Impartation Healing (WIH) which was attended by 120 participants from the different YFJ campuses, FOFJ ministries and their families. The goal of the WIH is to activate the prophetic gift and impart God's prophetic healing word for the purpose of building up His church.

In October, the YFJ undertook its first RO-RO mission to visit FOFJ missionaries Beng and Arla, and to hold a Worship Impartation Healing in Iloilo. RO-RO refers to the roll-on/roll-off ferry boat that took them to Iloilo. God's promise to the Israelites that "He will go before you always" became a reality to the YFJ because God  took care of the old L300 van that they used, and all the other details that would otherwise delay or hamper the trip.

In 2004, the Community earnestly desired, expected and did greater things for God. The mission in Iloilo which started only in May 2003 held its Youth Camp in March 2004. By November, YFJ-lIoilo conducted its first WIH with all the singers, dancers and musicians coming from the group.

To raise up God's next  generation workers, FOFJ conducted a Kids' Training for the children of global MR leaders in April. A follow-up seminar was conducted in May to teach the FOFJ children workers how to pray for the sick and to activate other gifts of the Holy Spirit. A children's camp for the Intramuros and Sta. Cruz children ministriesw as also held in April. It was attended by some 30 children.

The FOFJ mission work in Pangasinan further  accelerated. A leadership training seminar for 25 church leaders was started in April and culminated with a   crusade and WIH in October that was attended by about 300 parishioners. FOFJalso conducted a Life in the Spirit Seminar for 70 women barangay leaders in June.Two of the prophecies that were often impressed upon the Community during theyear were a) the Lord is doing new things and b) He is changing the wind that is blowing through the Community. One of the new things that the Community implemented in 2004  is to dance in worship to the Lord in its prayer and worship gatherings. A new moving in the PNB Office Ministry ushered the start in August of a new Thursday prayer meeting with 30 members. In October, the PNB Office Ministry also conducted a BasicChristian Life Training for professionals from Pangasinan.

In November, the FOFJ held its biggest WIH at the Malate Catholic Scho ol Gym. The concert which had the theme "Messengers of Power" was attended by 800 people from various FOFJ communities and YFJ campuses

Going further into the power of God, the Community strived in 2005 to move into a new level of anointing and excellence in the task it has been assigned to do.

In April 2005, FOFJ fulfilled its dream to evangelize in Mindanao when a team of missionaries and student volunteer workers  together with Kuya Mon and Bro. Litoy conducted a 10-day mission, traveling by RO-RO vessels that took them to Sorsogon, Samar, Misamis Oriental and Agusan del Norte. The objective of the mission was to conduct Worship Impartation Healing concerts/gatherings to share God's love and power to people in churches and communities to be visited along the RORO route. The mission was undoubtedly the most challenging activity of the YFJ in 2005 but it was also a great learning experience not only for those who joined the mission but for the entire FOFJ community as well.

The Community continued with its Summer Literacy Program, this time focusing on the Street children Ministry in Sta. Cruz  and Intramuros. With the success of the WIH in attracting the youth to join the community, the 2005 Youth Camp was reengineered to a WIH youth camp to train new YFJ worship warriors, i.e. new band members, instrumentalists, singers and dancers for future WIHs. A special training was also conducted for participants who were more inclined to handling administrative matters. Other summer youth camps were organized by the Bulacan Community, the South Community, and YFJ-Iloilo. Children of MR members attended the Youth Advancement Program Leaders' Seminar and the Kids' Prophetic Activation Seminar.

The Lord opened more opportunities for the Community to evangelize other sectors. In February, the Community conducted a one-day training  for about  40 middle-level regional training officers  of  the Philippine National Police who were then undergoing a month-long leadership andvalues training in Subic, Zambales. The FOFJ seminar focused on the topic "Becoming a Person of Influence". As a result of the first WIH conducted in February by the Bureau of Plant Industry Office Ministry at their Quezon City office, the Lord opened an opportunity for the FOFJ to hold another WIH, a youth training and a Kids' Bible study in May 2005 at the BPI office in Baguio City.

Through the years, the command in Isaiah 54:2 to "enlarge the place of your tent ...lengthen your cords and strengthen your stakes" was consistently repeated in the various times of prayer and fasting of the Community. After praying for this message and accomplishing in 2005 the difficult mission of traveling by RO-RO from Manila to Mindanao to conduct Worship Impartation Healing in different communities and churches, the Community decided that  it was time to move to a new mission post.

FOFJ started 2006 by sending its first missionary team to Mindanao. BengTacda and Abie Cruz were tasked to pioneer the mission to set up Young Flames for Jesus campus ministries initially in colleges  and universities in Cagayan de Oro City. In less than two months, FOFJ was given the opportunity to be heard and to influence 63 faculty and non-teaching staff of the Mindanao Polytechnic State College (MPSC) through a recollection that was held in March 2006. A recollection for 300 graduating students of MPSC was held simultaneously by the high power team of FOFJ Elders.

God was truly blessing the progress of the Mindanao mission. By April 2006, eleven YFJ Cagay-anons completed the one-day Leadership Training Seminar conducted by Beng and Abie. With the start of the new school year, YFJ-Cagayan de Oro held its first Worship Impartation Healing concert with the theme "Awaited Generation" in July at MPSC. In October, the Community
conducted  its first youth camp in Mindanao,which was attended by YFJ leaders of MPSC,  Liceo de Cagayan University and   Cagayan de Oro College (COC). Another WIH was held at the COC in November, followed by a Leadership Training Seminar for YFJ members which produced 15 student volunteer workers.

During the year, the Lord continued to do new things in the Community. For the first time in the history of the YFJ youth camps, there were more male than female participants in the YFJ Beginners' Youth Camp in March 2006. With the growing male membership of the YFJ and their increasing participation in YFJ activities, the community held in August  its first all-male sponsored  WIH which featured a male worship leader and all-male band, dancers, and skit presentors. The same moving encouraged the South Community to form its all-male choir.

Another first for the Community wasthe FOFJ Children Ministry Global Gathering with the theme "Buhay Masaya, Buhay
Masagana" in October 2006. The fun-filled children's party featured presentations from the Wedded Hearts for Jesus Kids ministry and the Children Ministries in Sta. Cruz, T.S.Cruz and Intramuros.

The Community also held one-month summer classes for grade school students in Umpucan, San IIdefonso, Bulacan to supplement their reading, writing, and speaking skills.

Overall, the Community had the most number of missionaries, conducted more trainings and seminars in all its ministries and local communities, and activated more spiritual gifts in 2006.

</pre>

	
</div>