<div class="content col-md-8" id="content">
	<b><h1 style="font-size:180%" class="section-title">FOFJ Starts to Fulfill its Mandate to be The Light to the Nations</h2></b>
	<pre style="font-size:150%">In the mid-eighties, FOFJ vigorously conducted outreach missions in offices and provinces that would later become local communities and affiliates of  FOFJ. Among the local communities were the San Mateo Community, Angels of Eloim in Lolomboy, Bulacan, and the San IIdefonso Community also in Bulacan. The affiliates were the Bulihan and GMA Charismatic Communities in Cavite and the Parish Pastoral Council members and ME members in Bolinao, Bani and Salasa, Pangasinan. There were also summer outreaches in Pangasinan  and Cabanatuan City while a group of Elders went to Dumaguete City to conduct healing crusades. FOFJ also started its weekly healing outreach in Philippine General Hospital (PGH). At present, the PGH Ministry is a shared activity of the PNB Office Ministry, the Makati Group and FOFJ Center.

Through the mighty moving of the Holy Spirit, more people attended the numerous Life in the Spirit and Growth Seminars, Leadership Seminars, and Workers' Training Seminars conducted  by the FOFJ under the supervision of Kuya Mon for its various prayer groups, local communities and affiliates.

Another factor that contributed to the rapid progress of the FOFJ was the fact that Kuya Mon opted to retire from PNB when the Bank offered an early retirement program in1986 to become a fulltime Elder, preacher, trainer and worker missionary of FOFJ. Inspired by the missionary mandateof the Community, several young FOFJ members also became fulltime FOFJ missionaries. Nap Callos, Claro Lavilla and Rudy Pederio stayed for three years (1987 to 1989) as fulltime missionaries in the residence of the Parish Priest of Bolinao, Msgr. Zosimo Navata, to undertake the mission to saturate Pangasinan with the Word of God. In the latter part of their mission work, they were joined by Liza Batac, followed by MaricrisTayo and Chat Ramirez, who were then tasked to help in operating the new radio station of the Diocese of Alaminos.

In the late eighties,  FOFJ also conducted outreach missions in Bicol to evangelize isolated and far-flung communities. During the mid-eighties up to the mid-nineties,  FOFJ  was blessed to have two spiritual directors, namely,Fr. Ramon Salinas, O.P. who guided theFOFJ in its overall thrusts and programs and Msgr. Zosimo Navata who guided the FOFJ in its mission work in Pangasinan. Fr.Salinas became the FOFJ Spiritual Director in the mid-eighties after Fr. Fitzgerald was reassigned to the US by his congregation.

</pre>

	
</div>